[package]
name = "latch-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
latch-core = { path = "../latch-core" }
latch-exec = { path = "../latch-exec" }
latch-fs = { path = "../latch-fs" }
latch-protocol = { path = "../latch-protocol" }
tracing.workspace = true

[lints]
workspace = true
