[package]
name = "latch-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[[bin]]
name = "LatchDesktop"
path = "src/main.rs"

[target.'cfg(windows)'.dependencies]
dirs.workspace = true
latch-link = { path = "../latch-link" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-single-instance = "2"

[target.'cfg(windows)'.build-dependencies]
tauri-build = { version = "2", features = [] }

[lints]
workspace = true
